layout_spectrum: 0.8781362
color:
  saturation: 0.06746493
  brandStrength: 0.7992831
  lightness: 0.2882407
  rhythmicContrast: 0.1571592
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 0.4892473
name: Trilaxy
