name: Trilaxy
favicon: null
layout_spectrum: 0.8781362
typography_spectrum: 0.75147
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.4856631
  lightness: 0.4086021
  saturation: 0.06746493
  rhythmicContrast: 0.1571592
purpose: []
